/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BotsIndexRouteImport } from './routes/bots/index'
import { Route as ApiCheckTokenRouteImport } from './routes/api/check-token'

const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckTokenRoute = ApiCheckTokenRouteImport.update({
  id: '/api/check-token',
  path: '/api/check-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/check-token': typeof ApiCheckTokenRoute
  '/bots': typeof BotsIndexRoute
}
export interface FileRoutesByTo {
  '/api/check-token': typeof ApiCheckTokenRoute
  '/bots': typeof BotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/check-token': typeof ApiCheckTokenRoute
  '/bots/': typeof BotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/check-token' | '/bots'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/check-token' | '/bots'
  id: '__root__' | '/api/check-token' | '/bots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiCheckTokenRoute: typeof ApiCheckTokenRoute
  BotsIndexRoute: typeof BotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-token': {
      id: '/api/check-token'
      path: '/api/check-token'
      fullPath: '/api/check-token'
      preLoaderRoute: typeof ApiCheckTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiCheckTokenRoute: ApiCheckTokenRoute,
  BotsIndexRoute: BotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
